name: Build Assets
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0"
          elixir-version: "1.12.3"
      - run: npm install --prefix ./assets
      - run: npm run deploy --prefix ./assets
      - name: Mix Digest
        run: |
          export MIX_ENV=prod
          mix deps.get
          mix compile
          mix phx.digest
      - name: Uploads the static files
        uses: actions/upload-artifact@v2
        with:
          name: static javascript
          path: priv/static
